services:
  next-app:
    container_name: blog-portfolio
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - react-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NEXTJS_IGNORE_ESLINT=1
    command: ["pnpm", "dev", "--turbo"]

networks:
  react-network:
    driver: bridge
